# Generated by Django 2.2.7 on 2020-03-08 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apiary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa Pasieki')),
                ('description', models.TextField(verbose_name='Opis pasieki')),
                ('localization', models.TextField(null=True, verbose_name='Lokalizacja')),
                ('area', models.FloatField(null=True, verbose_name='Powierzchnia')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeeMother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.DurationField(auto_created=True, verbose_name='Wiek Matki')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa Matki')),
                ('bee_type', models.CharField(choices=[(1, 'Kraińska'), (2, 'Kaukaska'), (3, 'CT13')], max_length=64, verbose_name='Typ pszczoły')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeeHive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Pozostaw puste by nadać standardową nazwę', max_length=64, verbose_name='Nazwa Ula')),
                ('type', models.CharField(choices=[(1, 'Wielkopolski'), (2, 'Dadant'), (3, 'Warszawski'), (4, 'Inny')], max_length=64, verbose_name='Typ Ula')),
                ('apiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beehive.Apiary')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BeeFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, verbose_name='Nazwa rodziny pszczelej')),
                ('strength', models.IntegerField(verbose_name='Siła rodziny')),
                ('bee_hive', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beehive.BeeHive', verbose_name='Ul')),
                ('bee_mother', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beehive.BeeMother', verbose_name='Matka')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
