# Generated by Django 2.2.7 on 2020-03-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiary',
            old_name='localization',
            new_name='location',
        ),
    ]
