# Generated by Django 2.2.7 on 2020-03-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0002_auto_20200308_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='beehive',
            name='honey_taken_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='beehive',
            name='service_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='area',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiary',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='beefamily',
            name='bee_hive',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beehive.BeeHive'),
        ),
        migrations.AlterField(
            model_name='beefamily',
            name='bee_mother',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='beehive.BeeMother'),
        ),
        migrations.AlterField(
            model_name='beefamily',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='beefamily',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='beehive',
            name='type',
            field=models.CharField(choices=[(1, 'Wielkopolski'), (2, 'Dadant'), (3, 'Warszawski'), (4, 'Inny')], max_length=64),
        ),
        migrations.AlterField(
            model_name='beemother',
            name='age',
            field=models.DurationField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='beemother',
            name='bee_type',
            field=models.CharField(choices=[(1, 'Kraińska'), (2, 'Kaukaska'), (3, 'CT13')], max_length=64),
        ),
        migrations.AlterField(
            model_name='beemother',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
