# Generated by Django 2.2.7 on 2020-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0004_auto_20200310_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beemother',
            name='age',
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
