# Generated by Django 2.2.7 on 2020-03-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0005_auto_20200310_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beemother',
            name='age',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
