# Generated by Django 2.2.7 on 2020-03-11 22:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0007_beemother_born'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beemother',
            name='born',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
