# Generated by Django 2.2.7 on 2020-03-17 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0009_auto_20200313_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beemother',
            name='age',
            field=models.DurationField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
