# Generated by Django 2.2.7 on 2020-03-17 10:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beehive', '0010_auto_20200317_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beemother',
            name='age',
            field=models.DurationField(blank=True, default=datetime.timedelta(-1, 86399, 999991)),
        ),
    ]
